# Generated by Django 5.0.6 on 2025-06-29 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID del curso')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre del curso')),
                ('cupoCurso', models.IntegerField(verbose_name='Cupo del curso')),
                ('descripcion', models.TextField(verbose_name='Descripción del curso')),
                ('fechaInicio', models.DateField(verbose_name='Fecha de inicio')),
                ('imagen', models.ImageField(null=True, upload_to='fotos', verbose_name='Fotografia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
                'ordering': ['created'],
            },
        ),
    ]
